blog
AigulY/R7-blog pull request #1
Opened 2023-11-27 09:01 UTC by AigulY

lesson 3.1 Rails Basic.

2023-12-05 04:21 UTC, dsinn requested changes
Hey, all your committed code looks good. However, it seems that the post `body` is missing from the views and form. Could you follow [this video](https://teamtreehouse.com/library/ruby-on-rails-5-basics/updating-views) and commit those changes?

2023-12-05 04:21 UTC, dsinn commented on app/controllers/pages_controller.rb
> +        set_page
You don't need this line; `set_page` is already called on `edit` because of what you passed into `before_action` above.

2023-12-05 23:18 UTC, dsinn commented on app/views/posts/_post.html.erb
This view is still missing the body, but I didn't check if it's used anymore after you switched from `form_with(model: post)` to `form_for(post)`. On a real project, you would verify this and either:

1. If this file is still needed, delete it;
2. Otherwise, delete it.

I would call this optional, as it's straightforward enough that I think this assignment has already its purpose.

2023-12-05 23:18 UTC, dsinn approved these changes

2023-12-06 22:09 UTC, AigulY commented on app/views/posts/_post.html.erb
Hey Daniel!
Looks like I don't need this file anymore.... Since I commented out the codes and everything works as expected. Do you want me to re-submit the changes or can I delete it with the following changes in the associations branch? I followed the instructions from the video completely, and I probably missed the part where this file is deleted, otherwise I don't understand where I made a mistake...

2023-12-07 07:22 UTC, merged